// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.OmniCoreDrill {
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
	[SuppressMessage("ReSharper", "FieldCanBeMadeReadOnly.Local")]
	[SuppressMessage("ReSharper", "ConvertPropertyToExpressionBody")]
	public partial class DefNames {
		public const string @Thing_CoreDrill = @"CoreDrill";
		public const string @Thing_UnfinishedDrillingPlan = @"UnfinishedDrillingPlan";
	}
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
	[SuppressMessage("ReSharper", "FieldCanBeMadeReadOnly.Local")]
	[SuppressMessage("ReSharper", "ConvertPropertyToExpressionBody")]
	public partial class DefReferences {
		private static Verse.ThingDef _Thing_CoreDrill = Verse.DefDatabase<Verse.ThingDef>.GetNamed(DefNames.Thing_CoreDrill);
		private static Verse.ThingDef _Thing_UnfinishedDrillingPlan = Verse.DefDatabase<Verse.ThingDef>.GetNamed(DefNames.Thing_UnfinishedDrillingPlan);
		public static Verse.ThingDef @Thing_CoreDrill { get { return _Thing_CoreDrill; } }
		public static Verse.ThingDef @Thing_UnfinishedDrillingPlan { get { return _Thing_UnfinishedDrillingPlan; } }
	}
}
