// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.OmniCoreDrill {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class LanguageKeys {
		public static class @keyed {
			/// <summary>
			/// Get's the translation key for '<em>mining deep {0}</em>'
			/// </summary>
			public const string @ocd_label = "ocd.label";
			/// <summary>
			/// Get's the translation key for '<em>mining deep {0}.</em>'
			/// </summary>
			public const string @ocd_description = "ocd.description";
			/// <summary>
			/// Get's the translation key for '<em>Mining deep {0}</em>'
			/// </summary>
			public const string @ocd_jobString = "ocd.jobString";
		}
	}
}
